services:
  - type: web
    name: dental-clinic-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean compile -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 17
